stages:          # List of stages for jobs, and their order of execution
  - build

build:
  stage: build
  image: docker:18-git
  services:
    - docker:18-dind
  script:
    # get node app version from package.json for use in tagging docker image
    - apk update && apk add jq
    - export VERSION=`jq -r ".version" < ./package.json`
    # login to docker
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    # build and tag docker image
    # - docker build -t $CI_REGISTRY_IMAGE:$VERSION -t $CI_REGISTRY_IMAGE:latest .
    - docker build .
    # publish finished image
    # - docker push $CI_REGISTRY_IMAGE:$VERSION
    # - docker push $CI_REGISTRY_IMAGE:latest
