image: node:latest

before_script:
  - apt-get update
  - apt-get install -y ruby-dev
  - gem install dpl

stages:          # List of stages for jobs, and their order of execution
  - deploy


deploy-job:
  stage: deploy
  image: ruby:latest
  script:
    - echo "Deploying application..."
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
    - echo "Application successfully deployed."
  only:
    - master
